### ISSUE TITLE
nit: Possible misleading context definition in `createCaller`? 

### ISSUE THREAD

**Issue by samjcombs** [jherr/trpc-on-the-app-router#10]
### Thanks!

First of all, thank you for arguably the only NextJS 14 w/ App router + tRPC with an SSR example on the whole of the internets 🎉 !

### Ok, on to the nit: 

The `createCaller` function is designed to take in a context object (or a function that returns a context object), but here you are passing in a terminating link in `links`.  It doesn't appear 1/ that this terminating link is used anywhere in the example codebase or 2/ that passing in a terminating link here would even be advisable.

For trpc newbs like me, this one could be misleading, unless I'm missing some magic here?

Thoughts? 

https://github.com/jherr/trpc-on-the-app-router/blob/7455d307e0b0146a74f1ce1f1989ec0fc4ddcee1/src/app/_trpc/serverClient.ts#L5-L11

Seems it would be better to pass in a context with say, the current session info from an auth provider, or a db connection reference, or just an `{}`?

**Comment by jherr** [comment]
It's possible the API changed? It certainly worked when I wrote it. I'll
have a look when I get a chance. Let me know if you get it working in your
environment and what the fix was.

**Comment by samjcombs** [comment]
Thanks for the quick response! 

To be clear, your example works fine, its just that you are passing in a `links` array with terminating link in _as the context_.  I think that it can be safely removed from the example, and when people implement their own real contexts they won't feel they are breaking anything by having to remove that `links` array.  Hope that makes sense! 

Ultimately, something like this might be more valuable as an educational example (works with next14+trpc11): 
```
import { appRouter } from '@/server';
import { createCallerFactory } from '@/server/trpc';
import { getServerSession } from 'next-auth/next';

// example context using next-auth and global prisma object, burn your own to your needs...
const createContext = async () => {
  const session = await getServerSession();
  return {
    session,
    prisma
  };
};

const createCaller = createCallerFactory(appRouter); // trpc >= 10.45 requires the use of this factory method to createCallers 
export const serverClient = createCaller(await createContext());
```
