### ISSUE TITLE
When using a production build the initial data does not change after the build 

### ISSUE THREAD

**Issue by amirs18** [jherr/trpc-on-the-app-router#4]
When using a production build the initial data does not change after the build 

you can see in the video the bugs it creates

https://github.com/jherr/trpc-on-the-app-router/assets/47773960/aae36ca1-a64a-435a-a832-cc0dec9ee19c

 this only happens during the production build, not in the dev

**Comment by jherr** [comment]
No problem. Fixed with a force-dynamic.
