### ISSUE TITLE
TRPCClientError: "input" needs to be an object when doing a batch call

### ISSUE THREAD

**Issue by zklinger2000** [jherr/trpc-on-the-app-router#5]
Steps to reproduce:

Clone, npm install, run dev

When adding text and clicking submit button, we get the following error:
`TRPCClientError: "input" needs to be an object when doing a batch call...`

![Screen Shot 2023-08-30 at 4 31 01 PM](https://github.com/jherr/trpc-on-the-app-router/assets/9243287/418e3c7a-de04-4a9f-af8d-82a39909f403)

**Comment by jherr** [comment]
Works for me. The only difference that I can see in between my repro path and yours is that I use `pnpm`.

Also please don't post screenshots in issues. It doesn't help make the issue more clear. Use the Markdown triple-backtick syntax and paste the error from the console.
