### ISSUE TITLE
How to create nested routes?

### ISSUE THREAD

**Issue by paulwongx** [jherr/trpc-on-the-app-router#8]
When I try to create a nested route, it gives me an error.

```ts
const nestedRouter = router({
  greet: publicProcedure.query(() => "nested hello world"),
});


export const appRouter = router({
  greet: publicProcedure.query(async()=> "hello world"),
  nested: nestedRouter,
});
```

When I go to `http://localhost:3000/api/trpc/greet` it works, but not when I go to
`http://localhost:3000/api/trpc/nested/greet`. The error is
```cli
404
This page could not be found.
```

How can I make nested routes work with app dir?

**Comment by jherr** [comment]
This is not an issue with this application. Feel free to ask this question on the tRPC Discord or Blue Collar Coder Discor.

**Comment by sakhshijan** [comment]
> When I try to create a nested route, it gives me an error.
> 
> ```ts
> const nestedRouter = router({
>   greet: publicProcedure.query(() => "nested hello world"),
> });
> 
> 
> export const appRouter = router({
>   greet: publicProcedure.query(async()=> "hello world"),
>   nested: nestedRouter,
> });
> ```
> 
> When I go to `http://localhost:3000/api/trpc/greet` it works, but not when I go to `http://localhost:3000/api/trpc/nested/greet`. The error is
> 
> ```
> 404
> This page could not be found.
> ```
> 
> How can I make nested routes work with app dir?

you can access to it http://localhost:3000/api/trpc/nested.greet
